import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./assets/styles/globals.css";
import Header from "./components/header";
import Navbar from "./components/navbar";
import { Nunito_Sans } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
  src:  "./assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  src:  "./assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by udemig",
};

export const nunito = Nunito_Sans({
  subsets:["latin"],
  variable:"--font-nunito",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex min-h-screen">
        <Navbar /> 

        <div className="flex flex-col w-full">
        <Header />
     <main className="flex-1 w-full bg-[#F5F6FA] p-5">{children}</main>
        </div>
        </div>

        <ToastContainer />
      </body>
    </html>
  );
}
